# Generated by Django 5.0.7 on 2024-07-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=255)),
                ('user_description', models.TextField()),
                ('lang', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lang', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('retweet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='recommend.tweet')),
                ('reply_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_user', to='recommend.tweetuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.tweetuser')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('is_popular', models.BooleanField(default=False)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.tweetuser')),
            ],
        ),
    ]
