# Generated by Django 5.0.7 on 2024-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_rename_user_description_tweetuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetuser',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
