# Generated by Django 5.0.7 on 2024-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_tweetuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetuser',
            name='lang',
            field=models.CharField(max_length=50),
        ),
    ]
