# Generated by Django 5.0.7 on 2024-07-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_alter_tweetuser_lang'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hashtag',
            unique_together={('user', 'tweet', 'text')},
        ),
    ]
